// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATt0I_8kfVZx7zxbWdVzV7zqLK3hgLrIA',
    appId: '1:907574232167:web:790c750ddad2e5fd8c40c2',
    messagingSenderId: '907574232167',
    projectId: 'smenka-6995a',
    authDomain: 'smenka-6995a.firebaseapp.com',
    storageBucket: 'smenka-6995a.firebasestorage.app',
    measurementId: 'G-DC7KT1V1VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxIg-DIQJ-84cxXw_RwJd-c-pBJsTkLA',
    appId: '1:907574232167:android:5d3f0ccb1ddc53308c40c2',
    messagingSenderId: '907574232167',
    projectId: 'smenka-6995a',
    storageBucket: 'smenka-6995a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lJYMFX41E7eWDX5l_ZiTju-eV1p-Jnw',
    appId: '1:907574232167:ios:5d06744f95b07f078c40c2',
    messagingSenderId: '907574232167',
    projectId: 'smenka-6995a',
    storageBucket: 'smenka-6995a.firebasestorage.app',
    iosBundleId: 'com.becandier.smenka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6lJYMFX41E7eWDX5l_ZiTju-eV1p-Jnw',
    appId: '1:907574232167:ios:5d06744f95b07f078c40c2',
    messagingSenderId: '907574232167',
    projectId: 'smenka-6995a',
    storageBucket: 'smenka-6995a.firebasestorage.app',
    iosBundleId: 'com.becandier.smenka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATt0I_8kfVZx7zxbWdVzV7zqLK3hgLrIA',
    appId: '1:907574232167:web:c9f3fa2d799b30598c40c2',
    messagingSenderId: '907574232167',
    projectId: 'smenka-6995a',
    authDomain: 'smenka-6995a.firebaseapp.com',
    storageBucket: 'smenka-6995a.firebasestorage.app',
    measurementId: 'G-21Z604158L',
  );
}
